apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-person-api
    app: person-service
  name: udaconnect-person-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    service: udaconnect-person-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-person-api
    app: person-service
  name: udaconnect-person-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-person-api
  template:
    metadata:
      labels:
        service: udaconnect-person-api
        app: person-service
    spec:
      containers:
      - image: zoeid/udaconnect-person-api
        name: udaconnect-person-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: person-db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: person-db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: person-db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: person-db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: person-db-env
              key: DB_PORT
        - name: GRPC_HOST
          value: udaconnect-person-grpc
        - name: GRPC_PORT
          value: "5005" 
      restartPolicy: Always
