apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-person-grpc
    ms: person-service
  name: udaconnect-person-grpc
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
  selector:
    service: udaconnect-person-grpc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-person-grpc
    ms: person-service
  name: udaconnect-person-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-person-grpc
  template:
    metadata:
      labels:
        service: udaconnect-person-grpc
    spec:
      containers:
      - image: zoeid/udaconnect-person-grpc
        name: udaconnect-person-grpc
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: person-db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: person-db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: person-db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: person-db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: person-db-env
              key: DB_PORT
      restartPolicy: Always
