apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-api
    app: location-service
  name: udaconnect-location-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30002
  selector:
    service: udaconnect-location-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-api
    app: location-service
  name: udaconnect-location-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-api
  template:
    metadata:
      labels:
        service: udaconnect-location-api
        app: location-service
    spec:
      containers:
      - image: zoeid/udaconnect-location-api
        name: udaconnect-location-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: location-db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: location-db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: location-db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: location-db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: location-db-env
              key: DB_PORT
        - name: TOPIC_NAME
          value: location-events
        - name: KAFKA_SERVER
          value: "kafka:9092"
        - name: GRPC_HOST
          value: udaconnect-location-grpc
        - name: GRPC_PORT
          value: "5005" 
      restartPolicy: Always
