apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-consumer
    app: location-service
  name: udaconnect-location-consumer
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    service: udaconnect-location-consumer
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-consumer
    app: location-service
  name: udaconnect-location-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-consumer
  template:
    metadata:
      labels:
        service: udaconnect-location-consumer
        app: location-service
    spec:
      containers:
      - image: zoeid/udaconnect-location-consumer
        name: udaconnect-location-consumer
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: location-db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: location-db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: location-db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: location-db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: location-db-env
              key: DB_PORT
        - name: GRPC_HOST
          value: udaconnect-person-grpc
        - name: GRPC_PORT
          value: "5005"
        - name: KAFKA_HOST
          value: kafka
        - name: KAFKA_PORT
          value: "9092"
      restartPolicy: Always