kind: PersistentVolume
apiVersion: v1
metadata:
  name: location-postgres-volume
  labels:
    type: local
    service: location-postgres
    app: location-service
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/location-postgres"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: location-postgres-pv-claim
  labels:
    service: location-postgres
    app: location-service
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: location-postgres
  labels:
    service: location-postgres
    app: location-service
spec:
  type: ClusterIP
  selector:
    service: location-postgres
  ports:
   - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-postgres
  labels:
    service: location-postgres
    app: location-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location-postgres
  template:
    metadata:
      labels:
        service: location-postgres
        app: location-service
    spec:
      containers:
        - name: postgres
          image: postgis/postgis:12-2.5-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: location-db-env
                key: DB_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: location-db-secret
                key: DB_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: location-db-env
                key: DB_NAME
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: location-postgres-pv-claim
