kind: PersistentVolume
apiVersion: v1
metadata:
  name: zookeeper-volume
  labels:
    type: local
    app: zookeeper
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/zookeeper_data"  
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zookeeper-pv-claim
  labels:
    app: zookeeper
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: zookeeper
spec:
  type: ClusterIP 
  selector:
    app: zookeeper
  ports:
   - port: 2181
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: zookeeper-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper-server
        image: docker.io/bitnami/zookeeper:3.7
        ports:
        - containerPort: 2181
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: 'yes'
---
