apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-connection-api
    app: connection-service
  name: udaconnect-connection-api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30003
  selector:
    service: udaconnect-connection-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-connection-api
    app: connection-service
  name: udaconnect-connection-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-connection-api
  template:
    metadata:
      labels:
        service: udaconnect-connection-api
        app: connection-service
    spec:
      containers:
      - image: zoeid/udaconnect-connection-api
        name: udaconnect-connection-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: location-db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: location-db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: location-db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: location-db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: location-db-env
              key: DB_PORT
        - name: LOCATION_GRPC_HOST
          value: udaconnect-location-grpc
        - name: LOCATION_GRPC_PORT
          value: "5005" 
        - name: PERSON_GRPC_HOST
          value: udaconnect-person-grpc
        - name: PERSON_GRPC_PORT
          value: "5005"
      restartPolicy: Always
