swagger: "2.0"
info:
  version: "1.0.0"
  title: "Swagger UdaConnect"
  contact:
    email: "hedi.abed.0@gmail.com"
host: "localhost:30012"
basePath: "/api"
tags:
- name: "persons"
  description: "Everything about creating and retrieving a Persons"
- name: "locations"
  description: "Everything about creating and retrieving a Persons locations"
- name: "connections"
  description: "Retrieving connections close to a person"
schemes:
- "http"
paths:
  /persons:
    post:
      tags:
      - "persons"
      summary: "Add a new person to the app"
      description: ""
      operationId: "addPerson"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "add a person to uda-connect app"
        required: true
        schema:
          $ref: "#/definitions/PersonSchema"
      responses:
        "405":
          description: "Invalid input"
        "201":
          description: "created"
          schema:
            $ref: "#/definitions/PersonSchema"
    get:
      tags:
      - "persons"
      summary: "get all persons"
      description: ""
      operationId: "getAllPersons"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/PersonSchema"
        "400":
          description: "Invalid status value"
  /persons/{person_id}:
    get:
      tags:
      - "persons"
      summary: "Find person by ID"
      description: "Returns a single person"
      operationId: "getPersonById"
      produces:
      - "application/json"
      parameters:
      - name: "person_id"
        in: "path"
        description: "Unique ID for a given Person"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/PersonSchema"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Person not found"
  /locations:
    post:
      tags:
      - "locations"
      summary: "Add a new location to the app"
      description: "Add location for an existing person"
      operationId: "addLocation"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "add a person to uda-connect app"
        required: true
        schema:
          $ref: "#/definitions/LocationSchema"
      responses:
        "405":
          description: "Invalid input"
        "201":
          description: "created"
          schema:
            $ref: "#/definitions/LocationSchema"
  /locations{location_id}:
    get:
      tags:
      - "locations"
      summary: "Find location by ID"
      description: "Returns a single location"
      operationId: "getLocationById"
      produces:
      - "application/json"
      parameters:
      - name: "location_id"
        in: "path"
        description: "Unique ID for a given location"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/LocationSchema"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Person not found"
  /connections:
    get:
      tags:
      - "connections"
      summary: "Find person by ID"
      description: "Returns a single person"
      operationId: "getConnections"
      produces:
      - "application/json"
      parameters:
      - name: "person_id"
        in: "query"
        description: "Unique ID for a given Person"
        required: true
        type: "integer"
        format: "int64"
        default: 6
      - name: "start_date"
        in: "query"
        description: "Lower bound of date range"
        required: true
        type: "string"
        format: "date-time"
        default: "2020-01-01"
      - name: "end_date"
        in: "query"
        description: "Upper bound of date range"
        required: true
        type: "string"
        format: "date-time"
        default: "2020-12-30"
      - name: "distance"
        in: "query"
        description: "Proximity to a given user in meters"
        required: true
        type: "integer"
        format: "int64"
        default: 5
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ConnectionSchema"
definitions:
  PersonSchema:
    type: "object"
    required:
    - "first_name"
    - "last_name"
    - "company_name"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 2
      first_name:
        type: "string"
        example: "Taco"
      last_name:
        type: "string"
        example: "Fargo"
      company_name:
        type: "string"
        example: "Udacity"
  LocationSchema:
    type: "object"
    required:
    - "person_id"
    - "longitude"
    - "latitude"
    - "creation_time"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 1
      person_id:
        type: "integer"
        format: "int64"
        example: 2
      longitude:
        type: "string"
        example: "-122.2222"
      latitude:
        type: "string"
        example: "37.3333"
      creation_time:
        type: "string"
        format: "date-time"
        example: "2022-03-15T10:37:06"
  ConnectionSchema:
    type: "object"
    properties:
      location:
          $ref: "#/definitions/LocationSchema"
      person:
          $ref: "#/definitions/PersonSchema"